[package]
name = "git-quest"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
directories = "6.0.0"
git2 = { version = "0.20.2", default-features = false }
